name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::708991919921:role/push-ecr-image
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: 708991919921.dkr.ecr.ap-southeast-2.amazonaws.com
          REPOSITORY: helm-tag-manager
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        env:
          REGISTRY: 708991919921.dkr.ecr.ap-southeast-2.amazonaws.com
          REPOSITORY: helm-tag-manager
          IMAGE_TAG: ${{ github.sha }}
        with:
          url: "https://jcg7s6payg.execute-api.ap-southeast-2.amazonaws.com/helm_tag_manager/"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.TAG_MANAGER_TOKEN }}"}'
          data: '{"message": {"commit_sha":"$IMAGE_TAG", "repo":"$REGISTRY/$REPOSITORY", "helm_chart_name":"helm-tag-manager-deployment", "namespace":"spend" }}'
